channels:
  - conda-forge
dependencies:
  - python>=3.8
  - sphinx
  - montreal-forced-aligner
  - pyside6
  - qt6-main
  - qt6-multimedia
  - pyqtgraph
  - librosa
  - myst-parser
  - numpydoc
  - pydata-sphinx-theme
  - sphinx-design
  - pip
